import discord
from discord.ext import commands
from github import Github
from pymongo import MongoClient
import base64
from mdutils.mdutils import MdUtils
import json

repo = None
readmeFile = None
mdFile = None
domains = None
f = open('config.json')
tokens = json.load(f)
conn_string = tokens['mongo_connection_string']
client = MongoClient(conn_string)
db = client.dscrait

def convertFromB64(encoded):
    base64_bytes = encoded.encode("utf-8")
    string_bytes = base64.b64decode(base64_bytes)
    string = string_bytes.decode("utf-8")
    return string 

def generateReadme():
    mdFile = MdUtils(file_name = "LOCAL_README.md")
    mdFile.new_header(level=1, title="Compilation Of DSC-RAIT resources")
    mdFile.new_paragraph("This is a ``README.md`` file generated by asmrPy to test it's capabilities. Stay tuned for more updates!")
    for d in db.resources.find():
        mdFile.new_header(level = 2, title = d['domain'])
        for l in d['links']:
            mdFile.new_paragraph(text=f"{l['info']}:{l['link']}")
    mdFile.create_md_file()
    text = mdFile.read_md_file(file_name = "LOCAL_README.md")
    return text
    
bot = commands.Bot(command_prefix = '!')

@bot.event
async def on_ready():
    global repo, readmeFile, mdFile, domains
    g = Github(tokens['github_token'])
    repo = g.get_repo("j23saw/asmr-test-lab")
    domains = []
    for d in db.resources.find():
        domains.append(d['domain'])
    print('We have logged in as {0.user}'.format(bot), domains)

@bot.command()
async def addDomains(ctx, *categories):
    global repo, readmeFile, mdFile, domains
    readmeFile = repo.get_contents("README.md")
    for c in categories:
        db.resources.insert_one({
            'domain': c,
            'links': []
        })
    repo.update_file(readmeFile.path, "file update",  generateReadme(), readmeFile.sha)
    await ctx.send(f'`{", ".join(categories)}` domains added successfully!')

@bot.command()
async def getDomains(ctx):
    global repo, domains
    n = "\n-".join(domains)
    text = f"```Domains are:\n-{n}```"
    await ctx.send(text)

@bot.command()
async def add(ctx, domain, info, link):
    global repo, readmeFile, mdFile, domains
    readmeFile = repo.get_contents("README.md")
    db.resources.update_one({'domain': domain}, {'$addToSet': {'links': {'info': info, 'link': link}}})
    repo.update_file(readmeFile.path, "file update",  generateReadme(), readmeFile.sha)
    await ctx.send(f'Added!')
    

bot.run(tokens['discord_token'])
